input_features:
  - CLOSE
  - VOL
  - PREM
  - DBLOW
  - REMAIN_SIZE
  - PCT_CHG
  - PCT_CHG_5
  - VOLATILITY_STK
  - PCT_CHG_STK
  - PCT_CHG_5_STK
  - LOG_MONEYNESS
  - PURE_VALUE
  - ALPHA_PCT_CHG_5
  - CAP_MV_RATE
  - TURNOVER
  - IV
  - VOL_STK_60
  - PREM_Z
  - PURE_VALUE_CS_RANK
  - PURE_VALUE_CS_ROBUST_Z
  - PREM_CS_RANK
  - PREM_CS_ROBUST_Z
  - REMAIN_SIZE_CS_RANK
  - CAP_MV_RATE_CS_RANK
